source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CDBDelegateCollection_Example', :exclusive => true do
  pod "CDBDelegateCollection", :path => "../"
end

target 'CDBDelegateCollection_Tests', :exclusive => true do
  pod "CDBDelegateCollection", :path => "../"

  
end
